### PR TITLE
fix: some handlers are mandatory before calling invoker

### PR DESCRIPTION
**Pull request by guillaumelamirand**
**Issue**

https://gravitee.atlassian.net/browse/ARCHI-445

**Description**

Initialize shadow handlers before calling the invoker to avoid some weird behavior (npe)

**Additional context**

---
**Gravitee.io Automatic Deployment**

🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
 - use it directly by updating your project with version: `2.0.2-archi-445-SNAPSHOT`
 - download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-traffic-shadowing/2.0.2-archi-445-SNAPSHOT/gravitee-policy-traffic-shadowing-2.0.2-archi-445-SNAPSHOT.zip)

### CODE REVIEW

**Comment by benoitgravitee** [comment]
Looks like you need update java compiler version to 17

**Comment by guillaumelamirand** [comment]
> Looks like you need update java compiler version to 17

I have updated the parent bom, it should be ok now.

**Review by benoitgravitee — APPROVED** [review]

**Pull request merged**
